// lib/core/constants/profile_options.dart
//
// ─── Static Profile Options ───────────────────────────────────────────────────
// Semua daftar pilihan statis untuk field profil pengguna dipusatkan di sini.
// JANGAN tulis array ini langsung di dalam file UI.
// ─────────────────────────────────────────────────────────────────────────────

abstract final class ProfileOptions {
  // ─── Location: Kota-kota Besar di Indonesia ─────────────────────────────────
  static const List<String> locationOptions = [
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Utara',
    'Jakarta Timur',
    'Bandung',
    'Surabaya',
    'Medan',
    'Semarang',
    'Makassar',
    'Yogyakarta',
    'Palembang',
    'Tangerang',
    'Depok',
    'Bekasi',
    'Bogor',
    'Denpasar',
    'Malang',
    'Pekanbaru',
    'Batam',
    'Banjarmasin',
    'Pontianak',
    'Balikpapan',
    'Samarinda',
    'Manado',
    'Padang',
    'Jambi',
    'Mataram',
    'Kupang',
    'Ambon',
    'Sorong',
    'Jayapura',
    'Cirebon',
    'Tasikmalaya',
    'Serang',
  ];

  // ─── Work: Profesi & Job Title Modern ───────────────────────────────────────
  static const List<String> workOptions = [
    'Student',
    'Software Engineer',
    'Mobile Developer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'UI/UX Designer',
    'Product Designer',
    'Product Manager',
    'Data Scientist',
    'Machine Learning Engineer',
    'DevOps Engineer',
    'Cloud Architect',
    'Cybersecurity Analyst',
    'Blockchain Developer',
    'Content Creator',
    'Digital Marketer',
    'Social Media Manager',
    'Brand Strategist',
    'Graphic Designer',
    'Motion Designer',
    'Video Editor',
    'Photographer',
    'Copywriter',
    'Game Developer',
    'AR/VR Developer',
    'Startup Founder',
    'Freelancer',
    'Business Analyst',
    'Financial Analyst',
    'Entrepreneur',
    'Educator / Lecturer',
    'Researcher',
  ];

  // ─── Education: Tingkat, Jurusan & Kampus Populer ───────────────────────────
  static const List<String> educationOptions = [
    'SMA / SMK',
    'D3 - Diploma',
    'D4 - Sarjana Terapan',
    'S1 - Sarjana',
    'S2 - Magister',
    'S3 - Doktor',
    'Teknik Informatika',
    'Sistem Informasi',
    'Ilmu Komputer',
    'Teknik Elektro',
    'Desain Komunikasi Visual',
    'Manajemen Bisnis',
    'Ilmu Komunikasi',
    'Ekonomi',
    'Psikologi',
    'Universitas Indonesia (UI)',
    'Institut Teknologi Bandung (ITB)',
    'Universitas Gadjah Mada (UGM)',
    'Universitas Airlangga (UNAIR)',
    'Institut Teknologi Sepuluh Nopember (ITS)',
    'Universitas Bina Sarana Informatika (UBSI)',
    'Universitas Brawijaya',
    'Universitas Diponegoro',
    'Binus University',
    'Universitas Padjadjaran (UNPAD)',
    'Telkom University',
    'Universitas Hasanuddin',
    'Universitas Mercu Buana',
    'STMIK / STIKOM',
  ];

  // ─── Hobbies: Migrasi dari setup_profile_page.dart ──────────────────────────
  // Dipindahkan ke sini agar halaman UI bebas dari array statis.
  static const List<String> hobbiesOptions = [
    'Coding',
    'Gaming',
    'Crypto',
    'Skateboarding',
    'Photography',
    'Music',
    'Design',
    'Content Creation',
    'Video Editing',
    'Stock Trading',
    'Anime / Manga',
    'Cafe Hopping',
    'Thrifting',
    'Movies & Series',
    'Fitness / Gym',
    'Traveling',
    'Futsal',
    'Strategy Games',
  ];
}
